### ISSUE TITLE
Create visual elements for notification

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#281]
- Survey deletion
- Deleting a category that has a question linked to it
- When trying to access a forbidden page logged out
- When creating anything
- Others you can think of

**Comment by JuanitoSebastian** [comment]
While making the backend functionality for this I thought about the types of notifications we display. I think we should break them to 3 categories: **Confirmation**, **Warning** and **Error**. 

- Confirmations convey to the user that an action was successful
- Warnings on the affects of an action. A warning does not necessarily block the user from doing an action.
- Error, something is invalid and the action is blocked
