### ISSUE TITLE
Add average score to each category to statistic page

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#323]
At the moment, the "get_categories_of_survey(survey_id)" is used to gather all the categories on the statistics page. Replace it with the function for getting scores. The lists gained from this function will have id on index 0 and name on index 1 (same as the previous function) and on index 2 it will have the average score. Insert this score either next to or below the name of each category.

**Comment by olenleo** [comment]
Done with a caveat:

Average scores to non-existing categories are linked to category_id: null as the database allows for a question with a category_weight referencing to a non-existent category. Questions and categories should be properly linked together when created through the app.
