### ISSUE TITLE
Add list of users who have answered the survey to statistic page

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#325]
The function returns the user id, email and group id of each user in addition to returning the date each user answered the survey. Make a list on the statistic page with these elements (with the exception of user id) shown of each user. Also have the number of users above the list. This number should already exist elsewhere (number of submissions) but it's good to have it next to the list so it can be updated once the users have been filtered while retaining the original number of submissions elsewhere. So don't use the submission count and instead use len on the list of users and give that value to the template. If possible, have the name of the survey, submission count and lists of categories and questions on the left side of the statistic page and the user list on the right side of the page. This way the page won't be horribly long and space is used more effectively. If this proves too much of an bother, just add the list of users to the bottom of the page. There is a separate task for finalizing the look of the page so it can be left there if necessary.

Once this task and at least one of the filtering functions has been made, the task for creating the corresponding filtering mechanism on the statistic page will no longer be blocked.

**Comment by jatufin** [comment]
Waiting for #330
