### ISSUE TITLE
When filtering users, update the average scores to match the new list of users

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#342]
Blocked until filtering buttons work and the average score counting function has been updated to support filtering. With only one filter button working, the task can be started but cannot yet be finished.

When users are filtered, call the average score counting function with the filters used and update the statistic page to show the updated average scores. Keep the original scores in so the user can compare them. Also make sure using the button for reversing the filter will remove the updated average scores.

**Comment by jatufin** [comment]
Status: Started
