### ISSUE TITLE
Fix answers created having lower id than existing answers on survey 1

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#352]
This has only been seen to happen on main heroku and only specifically on survey id 1. This was noticed since creating an answer added it to the top of the list instead of the bottom.

**Comment by jatufin** [comment]
Investigation:
- The id is created automatically by the database
- There is no guarantee in which order IDs are created, allthough usually they are incremented
- Checked the production datbase Questions id sequence:
```
> select last_value from "Questions_id_seq";
 last_value 
------------
         80
(1 row)
```
- Created a new question using the admin app, and checked the sequence value:
```
> select last_value from "Questions_id_seq";
 last_value 
------------
         81
(1 row)
```
- Currently the id sequence is behaving as it should

**Comment by jatufin** [comment]
The admin app has no control over the ID sequence value. Checked the daabase, and currently the id sequence has the highest value, as it should. The value also increments correctly when adding questions. It can not be ruled out the sequence value has been altered by hand.
