### ISSUE TITLE
Enable creating category results

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#390]
- [x] Divide the category edit page to two with one side including the list of content links and the option to add more and the other including the list of category results.
- [x] Have the existing category results be displayed with editable textboxes. The cutoff points can be potentially made with the same style as points and category weights on question page with only values between 0-1 being accepted.
- [x] Create the option to create a new category result below or above the list of existing results. When creating a new category result, be sure to update the updatedAt of the category and survey related to it. Give the user a warning if the parameters given are invalid. The cutoff points should, for example, not be identical to any existing ones.

Doing this task frees up tasks #392 and #394

**Comment by olenleo** [comment]
Split off the first one into #398
