### ISSUE TITLE
Enable creating survey results

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#391]
- [x] Add to the survey view a link or button which takes the user to a page for managing the survey results of the survey. The URL could be "surveys/[survey_id]/results" for example.
- [ ] On the page, have the existing survey results be displayed with editable textboxes. The cutoff points can be potentially made with the same style as points and category weights on question page with only values between 0-1 being accepted.
- [ ] Create the option to create a new survey result on the page. When creating a new survey result, be sure to update the updatedAt of the survey. Give the user a warning if the parameters given are invalid. The cutoff points should, for example, not be identical to any existing ones

Doing this task frees tasks #395 and #393

**Comment by Ronttikasa** [comment]
- [ ] show error when trying to create a result with existing cutoff value (handle db returning nonetype)

**Comment by Ronttikasa** [comment]
- Creating/editing is handled similarly to categories and questions i.e. on a separate page.
- The list of results is displayed on the main survey page
