### ISSUE TITLE
Enable editing survey results

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#393]
- Have the text and cutoff points be editable in each displayed survey result on the survey results page.
- Either add a separate button for saving edits or rename the add survey result button to save changes and have the button both update the changes made to existing survey results as well as create a new one if parameters were given for it
- If these changes would result in there being identical cutoff points or no cutoff points with the value of one or otherwise invalid parameters, make no changes and return a descriptive error message to the user
- If any changes have been made, also update the updatedAt of the survey related to the survey result(s) being updated

**Comment by jatufin** [comment]
- The update button already added in the PR #408 
- POST-handler: `/update_survey_result`
