### ISSUE TITLE
Average scores are not counted correctly when filtering

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#430]
With 2 answers with points 5 and 0 the result gained was 1.25. Also, in situations where the filter filters out all answers and no charts are made, an average score is counted.

Opened separate ticket for the second issue: #432 

Current status: Fixed

**Comment by jatufin** [comment]
The issue can be reproduced in the survey 8 ("elephants") statistics:
1. Enter "school" in the filter email field
2. Press filter
3. Average score on the first line is 1.25
4. The correct value should be 2.5

**Comment by jatufin** [comment]
Current status: Under investigation

**Comment by jatufin** [comment]
Fixes has been made, but the tests cause issues:

After adding `break` to the `survey_repository.py` line 993
in the test `survey_respository_test.py` line 936 and 943 test fail with previous values
