### ISSUE TITLE
Create warnings to surveys

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#437]
- Warning if there are questions without answers (fatal)
- Warning if there are questions without categories (problematic)
- Warning if there are categories without questions affecting them (problematic)
- Warning if there are categories without category results (fatal)
- Warning if there is no survey result (fatal)
- Show on homepage if survey has warnings (red for fatal, yellow for problematic). Green mark if no warnings

**Comment by JuanitoSebastian** [comment]
Warnings are:
- Puuttuu survey results
- Puuttuu kategorieat
- Kategoriat, joissa ei ole resultteja
- Ei kysymyksiä
- Kysymyksiä ilman vastausvaihtoehtoja
- Kysymyksiä, jotka eivät vaikuta kategorioihin
- Kategoria, johon ei vaikuta mikään kysymys
