### ISSUE TITLE
Make a function for checking if a survey has problems

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#438]
Make a function to survey repository which will take a survey id and return the following list  [status, no_survey_results, categories_without_results, questions_without_answers, questions_without_categories, categories_without_questions].
Also make a function to survey service which calls the function. Finishing this task opens up #440 and helps in finishing #439.

Give the values to the parameters in the list like this:

> no_survey_results = self.get_survey_results(survey_id) == []

> questions_without_answers = []
> questions = self.get_questions_of_survey(survey_id)
> for question in questions:
>> if self.get_question_answers(question[0]) == []:
>>>  questions_without_answers.append(question[1])

To get questions_without_categories, go through the category weights of each question (question[3]) in the above for loop and add the name of the question to questions_without_categories if there is no category with a non zero multiplier in the weights of the question. There is a json_into_dictionary function in helper.py which might be helpful. While doing this save the name of each category with a non zero multiplier in a list called categories_with_questions.

> categories_without_results = []
> categories_without_questions = []
> categories = self.get_categories_of_survey(survey_id)
> for category in categories:
>> if self.get_category_results_from_category_id(category[0]) == []:
>>> categories_without_results.append(category[1])

>> if category[1] not in categories_with_questions:
>>> categories_without_questions.append(category[1])

> if no_survey_results or categories_without_results or questions_without_answers:
>> status = "red"

> elif questions_without_categories or categories_without_questions:
>> status = "yellow"

> else:
>> status = "green"

> return [status, no_survey_results, categories_without_results, questions_without_answers,
> questions_without_categories, categories_without_questions]

**Comment by olenleo** [comment]
`check_survey_status()` recieves a survey id and returns a list as follows:
```
[           
            status :                        (str) 'red','yellow' or 'green',
            no_survey_results               (bool),
            no_categories                   (bool),
            categories_without_results :    (list) [category names],
            no_questions :                  (bool),
            questions_without_answers :     (list) [question names],
            questions_without_categories :  (list) [category names],
            categories_without_questions :  (list) [category names]
]
```
