### ISSUE TITLE
Implement a warning to survey view when survey has problems

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#439]
There will be a function made in #438  which will return the following list:  [status, no_survey_results, categories_without_results, questions_without_answers, questions_without_categories, categories_without_questions]

Status will be a string (green/yellow/red), no_survey_results a bool (True/False) and the rest will be lists of the categories or questions which have the problem. An empty list will mean that the survey doesn't have that problem. The functionality for this task can be done before #438 is done by hardcoding a list matching the one the function would give but if the task is done finishing this task will be more convenient.

Have a green check mark next to or above the name of the survey if the status is Green. Otherwise have it be a yellow or red exclamation mark. Make it so that hovering over or clicking this mark will list the user all the problems found and give an explanation for the mark (green=all good, yellow=might want to fix, red=fatal problems as in the survey cannot be answered). Also tell the user how these problems can be fixed. For example, give an answer to this and this question or consider adding weights to this question.

**Comment by AnttiVainikka** [comment]
The function to be used is check_survey_status() which takes a survey id and returns a list as follows:

[           
            status :                        (str) 'red','yellow' or 'green',
            no_survey_results               (bool),
            no_categories                   (bool),
            categories_without_results :    (list) [category names],
            no_questions :                  (bool),
            questions_without_answers :     (list) [question names],
            questions_without_categories :  (list) [category names],
            categories_without_questions :  (list) [category names]
]

**Comment by jatufin** [comment]
In #441 added a 9th field to the result list of `check_survey_status()`:
```
            A dictionary, where the key is the question id,
            and values are a list of category names:
            {1: ["foo", "bar"], 5: ["baz"]}
```
