### ISSUE TITLE
Add the status of each survey to homepage

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#440]
Call the function made in #438 for every survey to find out their status (it's index 0 from the list the function returns) and add it to the information relayed to the homepage. Then, depending if the status is green, yellow or red, add a green check mark or a yellow or red exclamation mark to the top right of each survey box on homepage.

Current status: Completed and waiting for merge

**Comment by jatufin** [comment]
Left appearance adjustments to be done in more general UI/UX tasks.
