### ISSUE TITLE
Filtered averages incorrect in some cases

### ISSUE THREAD

**Issue by Ronttikasa** [QueryAdmin-ohtu/SuperAdmin3000#452]
Filtered by date, three answers (non-registered users **not** included). Question 1 weighted points per answer: huge 5, nonexistent 0. Filtered average is 2.5, should be 3.33. Similar with question 2.

![Image](https://user-images.githubusercontent.com/44512829/203590357-e09eaf9f-7eb8-4150-ac68-9aa45f51a8b4.png)

Filtered by date, one answer (non-registered users included). Question 2 weighted points: forest 5. Filtered average is 2.5, should be 5.0.

![Image](https://user-images.githubusercontent.com/44512829/203595087-a55cced9-eaca-4a7c-825e-78ff291c859e.png)

In some cases the averages seem to be calculated correctly. Issue with total number of answers perhaps?

**Comment by jatufin** [comment]
Related #432
