### ISSUE TITLE
Figure out why random categories are listed in warning

### ISSUE THREAD

**Issue by AnttiVainikka** [QueryAdmin-ohtu/SuperAdmin3000#471]
![Image](https://user-images.githubusercontent.com/71161432/204799532-e31cdadc-6bc6-49f0-9c9d-9aeecfb9a00b.png)

The survey has no categories yet these categories are listed. I created a new survey with questions but no categories and this wasn't replicated. 

Link to the survey in question:
https://superadmin3000.herokuapp.com/surveys/6

**Comment by oskrsjlnd** [comment]
Categories of another survey are listed in the category weights of the survey
